### ISSUE TITLE
it does not work with RPi

### ISSUE THREAD

**Issue by sasagr** [adebayo10k/expressvpn-version-upgrader#1]
tried to use it on my raspberry pi but it does not download the right architecture.
I tried to manually change the 
detected_plat="U64" to
detected_plat="RPi"
in pkg-regexes.inc.sh

but it stills download the amd64.
Not sure where the error is. In any case could it be possible to put a self platform detector in the script?

**Comment by adebayo10k** [comment]
Hey, thanks for the heads up. I found a few problems that were probably causing the issue you discovered for the RPi. The main two were:
1. Literal errors in the static part of the `grep` pattern string. 
2. The `grep` pattern string was a bit overcomplicated, with variables for every little thing.
I think that when expressvpn web server gets a bad request for a package file, it just responds with the default 64-bit Ubuntu download. 

I moved the simplified `pkg_file_url` expressions into the function in **setup.in.sh** where they're actually being used. This code seems to work for the RPi:

`#Raspberry Pi OS`
``
pkg_file_url=$(curl -s "https://www.expressvpn.com/latest#linux" | \
grep -m 1 "https://www.expressvpn.works/clients/linux/expressvpn_[0-9\.-]*_armhf.deb" | \
sed 's/.*\(https\)/\1/; s/\(deb\).*/\1/') 
``

Yes, platform detector is probably due.

**Comment by sasagr** [comment]
Thanks!

Shall I pull it?
and just change the detected_plat to RPi?

if the platform detector is complicated maybe you could just add a platform selector, so we can choose when we lunch the script

**Comment by adebayo10k** [comment]
I'd test it on the command line first. See what string you get back from:
``
curl -s "https://www.expressvpn.com/latest#linux" | \
grep -m 1 "https://www.expressvpn.works/clients/linux/expressvpn_[0-9\.-]*_armhf.deb" | \
sed 's/.*\(https\)/\1/; s/\(deb\).*/\1/'
``
If that looks correct for you, then yes, pull and change to `detected_plat="RPi"`.
Ah, ok. That would be simpler to do.

**Comment by sasagr** [comment]
it seems to work but I see an error reading key.
Also if I run it again it does not seem to recognise that the newest version is already installed and it install it again.

pi@raspberrypi:~/expressvpn-version-upgrader $ ./expressvpn-version-upgrader.sh
"expressvpn" already installed OK
"gpg" already installed OK
"dpkg" already installed OK
"curl" already installed OK
"nmcli" already installed OK


Installed version:
expressvpn version 3.28.0.6-master - Release (0cc0a497)
Available version URL:
https://www.expressvpn.works/clients/linux/expressvpn_3.28.0.6-1_armhf.deb

Want to download the package and signature files? If not just terminate this program...
Enter q to quit program NOW, or just press ENTER to continue.


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.3M  100 16.3M    0     0  8597k      0  0:00:01  0:00:01 --:--:-- 8593k

Found an expressvpn package file: /home/pi/Downloads/expressvpn_3.27.1.0-1_armhf.deb


Found an expressvpn package file: /home/pi/Downloads/expressvpn_3.28.0.6-1_armhf.deb


NOW CHECKING package file AGAINST EXPRESSVPN PUBLIC KEY

gpg: error reading key: No public key
gpg: Signature made Thu 07 Jul 2022 06:09:44 EEST
gpg:                using RSA key xxxx
gpg: Can't check signature: No public key

Press ENTER to confirm a "Good signature"
Enter q to quit program NOW, or just press ENTER to continue.


Press ENTER to proceed with upgrade installation...
Enter q to quit program NOW, or just press ENTER to continue.


(Reading database ... 147898 files and directories currently installed.)
Preparing to unpack .../expressvpn_3.28.0.6-1_armhf.deb ...
Unpacking expressvpn (3.28.0.6-1) over (3.28.0.6-1) ...
Setting up expressvpn (3.28.0.6-1) ...
Upgrade in progress...
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
THE UPGRADE WAS SUCCESSFUL!

Here are the new version details:
expressvpn version 3.28.0.6-master - Release (0cc0a497)

Upgrade package file has been cleaned up after use OK

pi@raspberrypi:~/expressvpn-version-upgrader $

**Comment by sasagr** [comment]
also.. shouldn't it remove the downloaded file after installation?

**Comment by sasagr** [comment]
also even more interesting that after upgrade I still get.

pi@raspberrypi:~ $ expressvpn status
A new version is available, download it from https://www.vlycgtx.com/latest#linux.

Not connected
pi@raspberrypi:~

**Comment by adebayo10k** [comment]
Thanks for that output. Clearly the signature verification code is not working properly.
- Program assumes expressvpn public key has been imported.
- Program assumes a lot at the moment. Maybe bit too much.

Ok, I suppose I _should_ have said that I've done **zero** testing of this program on the RPi.

It's now clicked that yours is probably to main use case for this program. I have an RPi 3b+ that I'll try with. It has Raspbian buster, so wonder if that would take expressvpn?!?

- What model are you using? 
- Which OS? 
- Are you running it as a headless server, or wired desktop, or ...

Looks like it's not yet ready for the RPi just yet.

**Comment by sasagr** [comment]
RPi 4
with Debian buster
headless server ... sometimes connected with VNC so maybe I could say that I have the desktop functionalities as well.

**Comment by adebayo10k** [comment]
Do you have the expressvpn public key installed, as explained by [this expressvpn guide to verifying package authenticity](https://www.expressvpn.com/support/vpn-setup/pgp-for-linux/)? I'm hoping you don't, otherwise I don't have a clue what went wrong.
Their public key is 'key' to the whole verification process, so definitely worth it. I'm now thinking the program needs to check this in advance, soon after launch, maybe?

**Comment by adebayo10k** [comment]
The output would be this:
``
NOW CHECKING package file AGAINST EXPRESSVPN PUBLIC KEY

pub   rsa4096 2016-01-22 [SC]
      1D0B 09AD 6C93 FEE9 3FDD  BD9D AFF2 A141 5F6A 3A38
uid           [ unknown] ExpressVPN Release <release@expressvpn.com>
sub   rsa4096 2016-01-22 [E]

gpg: Signature made Thu 07 Jul 2022 04:09:39 BST
gpg:                using RSA key 1D0B09AD6C93FEE93FDDBD9DAFF2A1415F6A3A38
gpg: Good signature from "ExpressVPN Release <release@expressvpn.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1D0B 09AD 6C93 FEE9 3FDD  BD9D AFF2 A141 5F6A 3A38

GPG VERIFICATION PASSED OK, BUT AUTHORISE MANUALLY ANYWAY...
Press ENTER to confirm a "Good signature"
Enter q to quit program NOW, or just press ENTER to continue.
``

**Comment by sasagr** [comment]
you are right! I did not install it. I did it now. Here the all output

pi@raspberrypi:~ $ gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0xAFF2A1415F6A3A38
gpg: key AFF2A1415F6A3A38: public key "ExpressVPN Release <release@expressvpn.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
pi@raspberrypi:~ $ cd expressvpn-version-upgrader/
pi@raspberrypi:~/expressvpn-version-upgrader $ ./expressvpn-version-upgrader.sh
"expressvpn" already installed OK
"gpg" already installed OK
"dpkg" already installed OK
"curl" already installed OK
"nmcli" already installed OK


Installed version:
expressvpn version 3.28.0.6-master - Release (0cc0a497)
Available version URL:
https://www.expressvpn.works/clients/linux/expressvpn_3.28.0.6-1_armhf.deb

Want to download the package and signature files? If not just terminate this program...
Enter q to quit program NOW, or just press ENTER to continue.


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.3M  100 16.3M    0     0  8501k      0  0:00:01  0:00:01 --:--:-- 8497k

Found an expressvpn package file: /home/pi/Downloads/expressvpn_3.27.1.0-1_armhf.deb


Found an expressvpn package file: /home/pi/Downloads/expressvpn_3.28.0.6-1_armhf.deb


NOW CHECKING package file AGAINST EXPRESSVPN PUBLIC KEY

pub   rsa4096 2016-01-22 [SC]
      1D0B 09AD 6C93 FEE9 3FDD  BD9D AFF2 A141 5F6A 3A38
uid           [ unknown] ExpressVPN Release <release@expressvpn.com>
sub   rsa4096 2016-01-22 [E]

gpg: Signature made Thu 07 Jul 2022 06:09:44 EEST
gpg:                using RSA key 1D0B09AD6C93FEE93FDDBD9DAFF2A1415F6A3A38
gpg: Good signature from "ExpressVPN Release <release@expressvpn.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1D0B 09AD 6C93 FEE9 3FDD  BD9D AFF2 A141 5F6A 3A38

GPG VERIFICATION PASSED OK, BUT AUTHORISE MANUALLY ANYWAY...
Press ENTER to confirm a "Good signature"
Enter q to quit program NOW, or just press ENTER to continue.


Press ENTER to proceed with upgrade installation...
Enter q to quit program NOW, or just press ENTER to continue.


(Reading database ... 147898 files and directories currently installed.)
Preparing to unpack .../expressvpn_3.28.0.6-1_armhf.deb ...
Unpacking expressvpn (3.28.0.6-1) over (3.28.0.6-1) ...
Setting up expressvpn (3.28.0.6-1) ...
Upgrade in progress...
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
THE UPGRADE WAS SUCCESSFUL!

Here are the new version details:
expressvpn version 3.28.0.6-master - Release (0cc0a497)

Upgrade package file has been cleaned up after use OK

pi@raspberrypi:~/expressvpn-version-upgrader $

**Comment by sasagr** [comment]
so now we are left with issue that the program does not match the installed version 3.28.0.6-master - Release (0cc0a497) with 3.28.0.6-1 so it install it anyway

**Comment by adebayo10k** [comment]
Good, good. 
`expressvpn version 3.28.0.6-master - Release (0cc0a497)`
This was of course just the basic `expressvpn -v` version check.
Of course, any confusing, contradictory information needs to be left out altogether. I'll do that now.
Nice one.

**Comment by sasagr** [comment]
Hi. Pulled latest updates today and got this error
pi@raspberrypi:~/expressvpn-version-upgrader $ ./expressvpn-version-upgrader.sh
/home/pi/expressvpn-version-upgrader/includes/helper.inc.sh: line 25: lib10k_check_program_dependencies: command not found

I # the line 25 and got this. Not sure what's happening.

pi@raspberrypi:~/expressvpn-version-upgrader $ ./expressvpn-version-upgrader.sh
1) Ubuntu_64_bit    3) Fedora_64_bit    5) Arch_64_bit      7) None
2) Ubuntu_32_bit    4) Fedora_32_bit    6) Raspberry_Pi_OS
Select your OS Platform to check online for VPN client updates (or choose None): 6

You Selected the "Raspberry_Pi_OS" OS platform. Nice!

This program has not been tested on the "Raspberry_Pi_OS" OS platform.


Usage:  expressvpn-version-upgrader.sh [dev|help]

Checks a public web page for latest product information.
Optionally downloads, verifies and installs latest package.

Be aware that this program is an interesting workaround, but
relies on a public data source that is not guaranteed to persist.
It should therefore not really be used outside of hobby and
development environments.
Read the source, extend and test if you wish.

dev     Run program in development only mode.

help    Show this text.

pi@raspberrypi:~/expressvpn-version-upgrader $

If I run ./expressvpn-version-upgrader.sh dev I get the exactly same output.

Please advise
Thanks

**Comment by adebayo10k** [comment]
Hey. Once again, thanks for the feedback.
I used the program yesterday, to update to Version: 3.29.0.10-1.
Could you start a separate Issue with the output from your last comment?
Thanks.

**Comment by adebayo10k** [comment]
All issues fixed.
