### ISSUE TITLE
lib10k_check_program_dependencies: command not found

### ISSUE THREAD

**Issue by sasagr** [adebayo10k/expressvpn-version-upgrader#2]
Hi. Pulled latest updates today and got this error
pi@raspberrypi:~/expressvpn-version-upgrader $ ./expressvpn-version-upgrader.sh
/home/pi/expressvpn-version-upgrader/includes/helper.inc.sh: line 25: lib10k_check_program_dependencies: command not found

I # the line 25 and got this. Not sure what's happening.

pi@raspberrypi:~/expressvpn-version-upgrader $ ./expressvpn-version-upgrader.sh

Ubuntu_64_bit 3) Fedora_64_bit 5) Arch_64_bit 7) None
Ubuntu_32_bit 4) Fedora_32_bit 6) Raspberry_Pi_OS
Select your OS Platform to check online for VPN client updates (or choose None): 6
You Selected the "Raspberry_Pi_OS" OS platform. Nice!

This program has not been tested on the "Raspberry_Pi_OS" OS platform.

Usage: expressvpn-version-upgrader.sh [dev|help]

Checks a public web page for latest product information.
Optionally downloads, verifies and installs latest package.

Be aware that this program is an interesting workaround, but
relies on a public data source that is not guaranteed to persist.
It should therefore not really be used outside of hobby and
development environments.
Read the source, extend and test if you wish.

dev Run program in development only mode.

help Show this text.

pi@raspberrypi:~/expressvpn-version-upgrader $

If I run ./expressvpn-version-upgrader.sh dev I get the exactly same output.

Please advise
Thanks

**Comment by adebayo10k** [comment]
There are possibly two separate things happening for you here. I'll try to address both, one at a time.
Apologies if I talk about things you're already aware of. Also, the way I use Git and GitHub may not actually be the most best-practice/professional.

Explanation of first issue:

So, the **expressvpn-version-upgrader.sh** script depends on some common functions written in a library script called **shared-bash-functions.inc.sh**.
That library script is part of _another_ GitHub repository called **shared-functions-library**.
So to enable access it from the **expressvpn-version-upgrader** repo, it's been 'cloned' into the project as a _submodule_.

Now, when you pull the latest **expressvpn-version-upgrader**, you ALSO have to pull the latest **shared-functions-library** submodule dependency.

You'll need to go into the submodule directory and do another git pull. 

`cd shared-functions-library && git pull`

If that works, the first error should disappear.

Alternatively, you could just `rm -rf` the whole **expressvpn-version-upgrader** repository and clone it all down again, but that's not ideal.

**Comment by sasagr** [comment]
cd shared-functions-library && git pull
it does not seem to be enough

pi@raspberrypi:~/expressvpn-version-upgrader $ cd shared-functions-library/
pi@raspberrypi:~/expressvpn-version-upgrader/shared-functions-library $ git pull
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

so eventually I went for the rm -rf option.
Now the first issue has been fixed.

What about the second? :)

**Comment by adebayo10k** [comment]
so... what are your outputs now of:
`cd shared-functions-library && git pull`
or
`cd shared-functions-library && git fetch && git merge origin/main`
`apt-cache show network-manager`

**Comment by adebayo10k** [comment]
I couldn't test on my RPi, but I assume no worries, Debian is Debian.
Repo updated. Good luck.

**Comment by sasagr** [comment]
> so... what are your outputs now of: `cd shared-functions-library && git pull` or `cd shared-functions-library && git fetch && git merge origin/main` `apt-cache show network-manager`

pi@raspberrypi:~/expressvpn-version-upgrader/shared-functions-library $ git pull
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

pi@raspberrypi:~/expressvpn-version-upgrader/shared-functions-library $ git fetch && git merge origin/main
Already up to date.
pi@raspberrypi:~/expressvpn-version-upgrader/shared-functions-library $ apt-cache show network-manager
Package: network-manager
Version: 1.14.6-2+deb10u1
Architecture: armhf
Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Installed-Size: 10700
Pre-Depends: init-system-helpers (>= 1.54~)
Depends: libaudit1 (>= 1:2.2.1), libbluetooth3 (>= 4.91), libc6 (>= 2.28), libcurl3-gnutls (>= 7.16.3), libglib2.0-0 (>= 2.43.2), libgnutls30 (>= 3.6.5), libjansson4 (>= 2.0.1), libmm-glib0 (>= 1.0.0), libndp0 (>= 1.2), libnewt0.52 (>= 0.52.20), libnm0 (= 1.14.6-2+deb10u1), libpolkit-agent-1-0 (>= 0.99), libpolkit-gobject-1-0 (>= 0.104), libpsl5 (>= 0.13.0), libreadline7 (>= 6.0), libselinux1 (>= 1.32), libsystemd0 (>= 221), libteamdctl0 (>= 1.9), libudev1 (>= 183), libuuid1 (>= 2.16), lsb-base, wpasupplicant, dbus, udev, adduser, libpam-systemd, policykit-1
Recommends: ppp, dnsmasq-base, iptables, modemmanager, crda, isc-dhcp-client
Suggests: libteam-utils
Breaks: ppp (>= 2.4.7-3~), ppp (<< 2.4.7-2+~)
Homepage: https://wiki.gnome.org/Projects/NetworkManager
Priority: optional
Section: net
Filename: pool/main/n/network-manager/network-manager_1.14.6-2+deb10u1_armhf.deb
Size: 2135596
SHA256: d9daa9839dc15191fb27119560900e2668b1f0084201d755711f5b70675cfefd
SHA1: d64d4c2bd7d3779faeead24f5f6daa362b4fd872
MD5sum: 7742c821612b8cd9884050d1e54da5c6
Description: network management framework (daemon and userspace tools)
 NetworkManager is a system network service that manages your network devices
 and connections, attempting to keep active network connectivity when
 available. It manages ethernet, WiFi, mobile broadband (WWAN), and PPPoE
 devices, and provides VPN integration with a variety of different VPN
 services.
 .
 This package provides the userspace daemons and a command line interface to
 interact with NetworkManager.
 .
 Optional dependencies:
  * ppp: Required for establishing dial-up connections (e.g. via GSM).
  * dnsmasq-base/iptables: Required for creating Ad-hoc connections and
    connection sharing.
    address configuration.
  * libteam-utils: Network Team driver allows multiple network interfaces to be
    teamed together and act like a single one. This process is called "ethernet
    bonding", "channel teaming" or "link aggregation".
Description-md5: 37d8cb3ea8a04daaa3cb64dd2738db83

pi@raspberrypi:~/expressvpn-version-upgrader/shared-functions-library $

**Comment by sasagr** [comment]
> I couldn't test on my RPi, but I assume no worries, Debian is Debian. Repo updated. Good luck.

 ./expressvpn-version-upgrader.sh dev

worked!

Just noticed a possible misspell in "Interactive"

1) Yes, start Interative Delete
2) No, Skip

Thanks

**Comment by adebayo10k** [comment]
Great!
If you have any more ideas to make this project more useful in the _real world_, let me know.
Your comments really helped to push it forward.
Thanks.
